// <auto-generated />
using System;
using Financas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Financas.Api.Migrations
{
    [DbContext(typeof(FinancasDbContext))]
    [Migration("20260722000000_RemoverDiaFechamentoCartao")]
    partial class RemoverDiaFechamentoCartao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Modelo do CartaoCredito sem DiaFechamento
            modelBuilder.Entity("Financas.Api.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite_cartao_credito");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_cartao_credito");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status_cartao_credito");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cartao_credito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
